Feature (#20)
* Added PR Worflow

* Added PR Worflow

* Create cherry-pick

* Rename cherry-pick to cherry-pick.yml

* Update README.md

* Update README.md (#2)

* Update cherry-pick.yml

* Feature branch (#3)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature branch (#4)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature branch (#5)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature branch (#6)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature branch (#7)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature branch (#8)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature branch (#9)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature branch (#10)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Dev (#16)

* Feature branch (#11)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature (#12)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Feature (#15)

* Update README.md

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

* Update cherry-pick.yml

diff --git a/.github/workflows/cherry-pick.yml b/.github/workflows/cherry-pick.yml
--- a/.github/workflows/cherry-pick.yml
+++ b/.github/workflows/cherry-pick.yml
@@ -64,8 +64,20 @@ jobs:
             git fetch origin $branch
             git checkout $branch
             
-            # Cherry-pick the squashed commit to the target branch
-            git cherry-pick $SQUASHED_COMMIT_SHA
-            # Push the cherry-picked commit to the target branch
-            git push origin $branch
+          # Cherry-pick the squashed commit to the target branch
+                git cherry-pick $SQUASHED_COMMIT_SHA || true  # Prevent failure on conflicts
+                
+                # Handle potential conflicts or empty commits
+                if [ "$(git status --porcelain)" ]; then
+                  if git status | grep -q "use 'git cherry-pick --continue'"; then
+                    # Conflicts resolved, continue cherry-picking
+                    git cherry-pick --continue
+                  elif git status | grep -q "use 'git cherry-pick --skip'"; then
+                    # Cherry-pick resulted in an empty commit, skip it
+                    git cherry-pick --skip
+                  fi
+                fi
+                
+                # Push the cherry-picked commit to the target branch
+                git push origin $branch
           done
